[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@coinfi-account/=src/',
    '@coinfi-account-lib/=src/libraries/',
    '@coinfi-account-diamond/=src/libraries/diamond/',
]
optimizer_runs = 100_000
via_ir = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
